#!/usr/bin/env php
<?php
use OpenPress\Config\Configuration;
use Phinx\Console\Command as Phinx;
use Symfony\Component\Console\Application;
use OpenPress\Console\Command\CreateSeedCommand;
use OpenPress\Console\Command\CreateMigrationCommand;

$app = require_once __DIR__ . "/boot/bootstrap.php";

$console = new Application();

$console->add((new Phinx\Breakpoint())->setName("db:breakpoint"));
$console->add((new CreateMigrationCommand($app))->setName("db:create"));
$console->add((new Phinx\Migrate())->setName("db:migrate"));
$console->add((new Phinx\Rollback())->setName("db:rollback"));
$console->add((new Phinx\Status())->setName("db:status"));

$console->add((new CreateSeedCommand($app))->setName("seed:create"));
$console->add((new Phinx\SeedRun())->setName("seed:run"));

$console->run();
