#!/usr/bin/env php
<?php
use OpenPress\Config\Configuration;
use Phinx\Console\Command as Phinx;
use Symfony\Component\Console\Application;

require_once __DIR__ . "/boot/bootstrap.php";

$app = new Application();

$app->add((new Phinx\Breakpoint())->setName("db:breakpoint"));
$app->add((new Phinx\Create())->setName("db:create"));
$app->add((new Phinx\Migrate())->setName("db:migrate"));
$app->add((new Phinx\Rollback())->setName("db:rollback"));
$app->add((new Phinx\Status())->setName("db:status"));

$app->add((new Phinx\SeedCreate())->setName("seed:create"));
$app->add((new Phinx\SeedRun())->setName("seed:run"));

$app->run();
